services:
  mongodb:
    image: mongo:latest
    container_name: btg-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: btg-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  orderms:
    build: .
    container_name: btg-orderms
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/orderms
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest

volumes:
  mongo-data:
